### PR TITLE
Fix sidebar width calculation

### PR DESCRIPTION
**Pull request by kugaevsky**
Use sidebar inner element width to calculate sidebar dimensions. Sidebar inner and outer elements could have different widths, but plugin sets outer width to inner element when in «sticky» mode.

### CODE REVIEW

**Comment by kugaevsky** [comment]
@abouolia is it ok or something wrong with this PR?

**Comment by abouolia** [comment]
Just needs review.

**Comment by kugaevsky** [comment]
Any progress here?

**Comment by abouolia** [comment]
You're right, thank you so much for pull request and i'm sorry for delay.

**Pull request merged**
